README.md

more detailed structure in readme

---

README.md

Je trouve ça plus cohérent de ne pas numéroter les pièces.

change ordered list to unordered list in readme site structure

---

init.sql

Ajoute le fichier init.sql qui créé les tables de la base de données.
Ajout également de la table "historique" pour visualiser les données des capteurs. Pensez donc à mettre à jours vos tables après la pull request

Création de la base de donnée

---

init.sql

pour une meilleur compréhension et une meilleur compatibilité avec les requêtes déjà présentes

change "mail" vers "email" dans la table utilisateurs

---

model/signInTreatment.php
model/signupTreatment.php

Chiffre les mots de passe à l'inscription avec "password_hash" utilisant l'algo "PASSWORD_DEFAULT".
Test ensuite au login avec "password_verify".

Password encrypt

---

controller/admin.php
view/sidebar.php

Adapte les boutons de la sidebar au domaine

Interactive sidebar

---

controller/admin.php
controller/functions.php
controller/home.php
controller/user.php
index.php
model/connectBDD.php
model/editionCompteTreatment.php
model/signInTreatment.php
model/supportTickets.php
public/css/headerAndFooter.css
public/css/login.css
public/css/mon_compte.css
public/css/notFound404.css
public/css/styles.css
view/admin-accounts-management.php
view/contact.php
view/functions.php
view/header.php
view/login.php
view/notFound404.php
view/sidebar.php
view/signup.php
view/template.php
view/user-compte.php

Onglet "Gestion comptes" de l'administrateur.
Lui permet d'afficher l'ensemble des comptes existants et, pour chacun, d'en modifier toutes les infos sauf le mot de passe.

Admin account management

---

controller/user.php
model/houses.php
public/css/styles.css
view/add-product.php
view/sidebar.php
view/template.php
view/user-dashboard.php
view/userLogements.php

Intègre la page de visualisation des logements, pièces et capteurs afin d'y rajouter l'interface pour faire des modifications.
Le bouton, la page et le fonctionnement pour enregistrer un capteur est déjà en place.

User houses config

---

controller/user.php
model/ajoutLogementTreatment.php
public/css/mon_compte.css
view/ajoutLogement.php
view/sidebar.php

Merge afin d'intégrer les modifications avec l'ajout de capteur

Ajout logement

---

controller/user.php
view/add-product.php
view/userLogements.php

Intègre les ajouts récent pour l'ajout d'un nouveau produit ou d'une nouvelle maison

Link new house

---

init.sql

Ajoute le champ "action" à la table "logs" dans la BDD

Db log fix

---

controller/admin.php
init.sql
model/logsTreatment.php
model/supportTickets.php
public/css/ticketSupport.css
public/js/ticketSupport.js
view/support.php

Traitement tickets de support : affichage + réponses + changement de statut

Ticket de support

---

controller/admin.php
controller/user.php
model/ajoutLogementTreatment.php
model/editionCompteTreatment.php
model/houses.php
public/css/modal.css
public/css/mon_compte.css
public/css/styles.css
public/js/deletePost.js
public/js/deleteUser.js
public/js/modal.js
view/template.php
view/user-compte.php
view/userLogements.php

Permet la suppression des logements et des produits via l'interface utilisateur

Suppression elements

---

controller/home.php
public/css/mentions-legales.css
view/home-footer.php
view/mentions-legales.php
view/sidebar.php

La page des CGU est prête. Lien vers contact en bas de page fonctionnel header et mise en forme. Pour moi, il n'y a pas besoin de la side bar ou d'un font, c'est une page "formelle".

Mentions legales

---

controller/admin.php
init.sql
model/productsTreatment.php
public/css/products.css
view/gestionProduits.php
view/sidebar.php

- création nouvelle table modeleProduit pour admin
-ajout et suppression de modele
- choix icone des modeles
-ajout modele dans BDD si modele pas déjà existant, sinon, alert

Gestion produits

---

controller/user.php
model/houses.php
public/css/headerAndFooter.css
public/css/styles.css
view/ajoutLogement.php
view/user-dashboard-conso.php
view/user-dashboard.php

Page dashboard terminée, css peaufiné, il manque juste l'ajout des graphiques

Graph conso

---

model/houses.php
public/css/styles.css
view/user-dashboard.php

Changement mineurs au niveau du dashboard utilisateur

User dashboard fix

---

controller/user.php
model/ajoutLogementTreatment.php
view/userLogements.php

Supprime les pièces lorsqu'un logement est supprimé et empêche la suppression de logement non vide

Clean house delete

---

model/houses.php

Home after login

---

controller/home.php
index.php
public/css/headerAndFooter.css
view/header.php

* Quand connecté, le logo redirige vers la page d'accueil
* L'icône d'utilisateur ouvre un menu pour se déconnecter
* Empêche l'accès aux domaines si non connecté

Better header

---

README.md
view/reception.php
view/sidebar.php

* Change un petit peu l'arrangement de la page d'accueil utilisateur
* Supprime l'onglet "Gestion utilisateurs" de la sidebar utilisateur

Small user fixes

---

index.php
model/signInTreatment.php
view/header.php

Permet de passer d'une interface à l'autre (client, gestionnaire, admin) à travers des boutons du menu déroulant en haut à gauche

Interface switch

---

controller/user.php
model/houses.php
model/tramesTreatment.php
pages/RecupTrames.php
public/css/actionneur.css
view/user-dashboard.php

- à ajouter après branche Affichage Valeurs 
- affichage actionneurs dans le dashboard
- enregistrement des états des actionneurs dans la BDD (table actionneurs) --> vérification php
- envoi des trames depuis le site vers la passerelle en cliquant sur l'actionneur

Envoi trames

---

controller/admin.php

Ajout des textes de logs pour : 
- changement de statut des tickets de support 
- ajout et suppression de modèle produit

Ajout text logs

---

controller/user.php
model/houses.php

- test d'existence de cemac dans la BDD, impossibilité d'ajouter une cemac déjà existante
-pop-up si tentative d'ajouter une cemac existante dans la BDD 
-test d'existence des capteurs et actionneurs reliés à la cemac avant la suppression 
-impossibilité de supprimer cemac avec des produits attribués
-si tentative de suppression de cemac possédant encore des produits,  affichage pop-up

Suppression cemac

---

model/productsTreatment.php

- ajout de l'ID des modèles correspondant aux ID de la liste des ID de capteurs de Domisep dans la colonne ID_modèle de la table modèleProduits

correspondance entre nom du modèle et icône

---

model/houses.php
view/graphe.php

Il manquait un " ]);" dans Houses, addproduct, qui faisait bugger le site

Remplace temperature par "valeur"

---

controller/admin.php
controller/user.php
model/houses.php
view/AjoutCemac.php
view/add-product.php
view/gestionProduits.php

-test l'existence de capteurs et d'actionneurs dans les tables propriétés produits, actionneurs et capteurs avant l'ajout

Test existence capteurs

---

controller/user.php
model/houses.php
view/user-dashboard-conso.php

Il manquait un " ]);" dans Houses, addproduct, qui faisait bugger le site

corrige les fonctions liées aux graphes
